name: yout
description: Learn a language by speaking and listening.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+15

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  audioplayers: ^5.1.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.1
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.7.0
  kana_kit: ^2.0.0
  shared_preferences: ^2.2.0
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"

# Generate all icons by running `dart run flutter_launcher_icons`
# https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../art/yatt-logo-1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/language_flags/
    - assets/sounds/
    - assets/translatordb/a1/
    - assets/translatordb/a1b/
    - assets/translatordb/a2/
    - assets/translatordb/b1/
