name: yout
description: Learn a language by speaking and listening.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.7.0
  shared_preferences: ^2.2.0
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translatordb/a1/
